### ISSUE TITLE
Error when trying to create world

### ISSUE THREAD

**Issue by grofit** [cucumber/cucumber-js#313] opened 2015-03-09 15:53 UTC
I have a strange issue where it is failing after `BeforeFeatures` but before `Before` where it dies trying to create the world object:

```
Unhandled rejection TypeError: undefined is not a function
  at Object.instantiateNewWorld (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\support_code\library.js:91:19)
  at Object.visitScenario (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:55:26)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\ast\feature.js:105:17
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at Object.forEach (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:62:7)
  at Object.instructVisitorToVisitScenarios (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\ast\feature.js:104:23)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\ast\feature.js:90:14
  at Object.instructVisitorToVisitBackground (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\ast\feature.js:99:9)
  at Object.acceptVisitor (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\ast\feature.js:89:12)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:43:38
  at callUserFunctionAndBroadcastAfterEvent (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:151:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:52:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at C:\Program Files (x86)\JetBrains\WebStorm 140.2753\plugins\CucumberJavaScript\lib\cucumberjs_formatter_windows.js:83:9
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:6:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at Object.forEach (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:62:7)
  at broadcastToListeners (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:178:19)
  at onRuntimeListenersComplete (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:174:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:52:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener\summary_formatter.js:16:7
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener\summary_formatter.js:15:18)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at Object.forEach (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:62:7)
  at broadcastToListeners (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:178:19)
  at Object.broadcastEvent (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:170:7)
  at Object.broadcastBeforeEvent (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:161:12)
  at Object.broadcastEventAroundUserFunction (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:145:12)
  at Object.visitFeature (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:41:12)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\ast\features.js:21:17
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at Object.forEach (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:62:7)
  at Object.acceptVisitor (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\ast\features.js:20:16)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:33:39
  at callUserFunctionAndBroadcastAfterEvent (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:151:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:52:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at handleBeforeFeaturesEvent (C:\Program Files (x86)\JetBrains\WebStorm 140.2753\plugins\CucumberJavaScript\lib\cucumberjs_formatter_windows.js:71:9)
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:6:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at C:\Code\Web\PrototypeA\tests\api-tests\features\support\shared-hooks.js:74:17
  at process._tickDomainCallback (node.js:486:13)
From previous event:
  at C:\Code\Web\PrototypeA\api-tests\features\support\shared-hooks.js:71:21
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:6:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at Object.forEach (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:62:7)
  at broadcastToListeners (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:178:19)
  at onRuntimeListenersComplete (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:174:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:52:11)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:59:11
  at hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener\summary_formatter.js:16:7
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener.js:8:9)
  at Object.hear (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\listener\summary_formatter.js:15:18)
  at C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:179:51
  at processItem (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:58:9)
  at iterate (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:50:11)
  at Object.forEach (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\type\collection.js:62:7)
  at broadcastToListeners (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:178:19)
  at Object.broadcastEvent (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:170:7)
  at Object.broadcastBeforeEvent (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:161:12)
  at Object.broadcastEventAroundUserFunction (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:145:12)
  at Object.visitFeatures (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:31:12)
  at Object.walk (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime\ast_tree_walker.js:20:12)
  at Object.start (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\runtime.js:19:21)
  at Object.runSuiteWithConfiguration (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\cli.js:19:15)
  at Object.run (C:\Program Files\nodejs\node_modules\cucumber\lib\cucumber\cli.js:12:14)
  at Object.<anonymous> (C:\Program Files\nodejs\node_modules\cucumber\bin\cucumber.js:4:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

Line 74 in shared hooks which it lists is the callback of the `BeforeFeatures` event handler.

The world file which resides within `/features/support/default-world.js` looks like:

```
module.exports = function() {
    this.World = function(callback) {
         // .. Some stuff
         callback();
    }
}
```

I even put a console.log as the first line to see if it even enters there but it doesn't seem to. So the error seems to happen at line 91 in library.js:
```
    instantiateNewWorld: function instantiateNewWorld(callback) {
      var world = new worldConstructor(function (explicitWorld) { // THIS BLOWS UP
        process.nextTick(function () { // release the constructor
          callback(explicitWorld || world);
        });
      });
```

So do I need to do anything else to get my world instance registered? I am using 0.4.8 and happy to provide more info if required.

**Comment by grofit** [comment] 2015-03-10 10:33
It appears to stem from the look for a default world constructor:

`SupportCode.WorldConstructor                   = require('./support_code/world_constructor');`

I never had this issue with previous versions so not sure if anything has changed in this version, although I am manually registering my worlds in the step definitions rather than naming convention.

**Comment by sam3k** [comment] 2015-04-17 17:03
I'm having the same issue with cucumber 0.4.8 and node 0.10.32

@grofit have you found a workaround?

**Comment by grofit** [comment] 2015-04-17 18:22
My cucumber stuff is working at the moment, but I cannot remember what I did to fix it :( but I am using 0.4.8 and Node 12.*. Although I know I dont do anything with the world object in `BeforeFeatures` I have a local object which stores the objects then in the `Before` method I populate the world object as it is in scope and works fine there. Maybe the fix was me to not touch the world object in the BeforeFeature, that help?

**Comment by sam3k** [comment] 2015-04-19 18:03
You might be right. I removed the afterhook exports which I have defined in the same file and the problem went away. Thanks!

**Comment by derrelldurrett** [comment] 2015-05-14 20:21
I've hit this as well. I am using node v0.12.0, and cucumber-js 0.4.8 (on Windows 7).

Any hints as to how to solve this, or failing that suggestions for data that would be helpful to others trying to solve this problem, gratefully accepted.

**Comment by jbpros** [comment] 2015-06-16 08:22
Is anyone still experiencing this problem as of 0.5?

I'm closing the issue but please reopen if needed. A complete file set demonstrating the problem would be great, I can't reproduce this.

**Closed by jbpros** 2015-06-16 08:22 UTC
