### ISSUE TITLE
Second scenario tests not triggering after completing first scenario in Windows

### ISSUE THREAD

**Issue by RanjitAwati** [cucumber/cucumber-js#1792] opened 2021-09-01 06:38 UTC
Hi all,
I'm getting error in hooks.js for the subsequent scenarios after completing first one. Getting error in Before function()
Browser launches and freezes (attached required Config files)

NOTE: The tests are working fine in my mac but in windows after the first scenario successful run, the subsequent test fails
![130734322-bd03d066-cb31-4cd9-84c2-9090be097080](https://user-images.githubusercontent.com/47976619/131623660-cc5866f7-b764-46ee-8725-3639f097823c.png)
<img width="792" alt="130908092-247bb891-4f36-4b1d-aab6-5cd177a38c7c" src="https://user-images.githubusercontent.com/47976619/131623670-8120b0bd-ad66-4f16-911e-08d7e0e6c531.png">

**Comment by aslakhellesoy** [comment] 2021-09-01 07:57
Can you please do the following:

* Instead of attaching a zip file, please provide a link to a git repository that contains everything we need to reproduce this behaviour. (Your zip file does not have any feature file nor does it have the `hooks.js` file you mention.
* Make sure you are using the latest version of `@cucumber/cucumber` and *remove* the deprecated `cucumber` from your dependencies

**Comment by RanjitAwati** [comment] 2021-09-01 12:04
@aslakhellesoy Please find the attached link for the details

https://drive.google.com/file/d/1JZI9IOzBwW_DIdB1Tu8L1sphei_oWElF/view?usp=sharing

**Comment by aurelien-reeves** [comment] 2021-09-01 12:09
@RanjitAwati please share a github repository rather than a zip file

Did you tried @aslakhellesoy suggestion regarding cucumber versions?

**Comment by RanjitAwati** [comment] 2021-09-01 12:15
@aurelien-reeves Yes I've tried with the latest version of @cucumber/cucumber and removing the reference to the deprecated version 
github link : https://github.com/TruRating/docs-core-testcafe-dash2tests

**Comment by aslakhellesoy** [comment] 2021-09-01 12:15
@RanjitAwati we won't be able to help you unless you create a git repo. Please keep it smaller than 100kb - your zip file is 100Mb(!)

**Comment by aslakhellesoy** [comment] 2021-09-01 12:16
That github link gives a 404

**Comment by RanjitAwati** [comment] 2021-09-01 12:50
@aslakhellesoy Here you go https://github.com/RanjitAwati/Testcafe-tests-das2

**Comment by aurelien-reeves** [comment] 2021-09-01 13:10
"cucumber" still appears in your package-lock.json due to some peer dependencies.
Make sure to remove it entirely

**Comment by davidjgoss** [comment] 2021-09-20 23:52
Closing as it looks like the cause was identified per previous comment.

**Closed by davidjgoss** 2021-09-20 23:52 UTC
Labels: :baby_bottle: incomplete, :question: question
