### ISSUE TITLE
determine which features use a step definition

### ISSUE THREAD

**Issue by laurelnaiad** [cucumber/cucumber-js#476] opened 2015-12-16 16:33 UTC
Ultimately , Cucumber determines which step definitions are involved in a feature file/scenario/step in order to execute the steps. Is there a way to access this information?

The reason I ask is that I'd like to map the dependencies such that when a file is changed, I can trace back to the feature files that are impacted and run only those tests.

```
someFeature.feature 
  depends on someSpecs.js
    depends on someSrcFile.js
```

If someSrcFile.js is changed, I can pretty easily determine that someSpecs.js is impacted, but I'd like to know that someFeature.feature is impacted , so I can do a cucumber run on that feature. Of course, in many cases there would be multiple specs files and thus multiple feature files impacted... the above is just a basic scenario.

I'm guessing that somewhere in Cucumber, the tree information is known, but I don't know where to go looking or whether that knowledge is exposed via API.

I'd love it if I could have cucumber parse the whole set of feature files without running any tests, and then query it to say, "for this specs file (someSpecs.js), which feature files depend on it?

Under [Running Specific Features](https://github.com/cucumber/cucumber-js#running-specific-features), I see that I can run a feature based on a scenario name. I guess what would be great is if there is an extension like

``` bash
# runs all features that depend on someSpecs.js
cucumber.js --specs someSpecs.js
```

but I'd also be perfectly content to make the determination of which features depend on someSpecs.js through the API... I don't necessarily need a CLI option, and in fact I think I'd rather be able to do this via the API so I can hang on to the information about the dependency(ies).

**Comment by charlierudolph** [comment] 2015-12-16 19:31
> Ultimately , Cucumber determines which step definitions are involved in a feature file/scenario/step in order to execute the steps. Is there a way to access this information?

At the moment, no.

---

Just to clarify, `someSpecs.js` contains step definitions correct? This seems related to #468 where we want to be able to get information about step definitions and there usage. I don't know if we can easily make a javascript API and this may more likely be a formatter that could output json.

**Comment by laurelnaiad** [comment] 2015-12-17 15:47
I just came across this: https://github.com/gaslight/atom-cucumber-step which purports to be able to find the step definition associated with a line from a feature file, as far as I can tell. I'm afraid to install it because I'm under a deadline and I've had bad luck with atom packages lately, but I wonder if it works as I read it to work, and if there's magic in there that I could harvest for my use case.

P.S. Yes, I meant to type some**Steps**.js, as that's a steps definition file in my example.

**Comment by charlierudolph** [comment] 2016-12-20 15:16
I'm going to close this as a duplicate of #468. As part of that, I am planning on a `usage` formatter which will output where each step definitions is used.

**Closed by charlierudolph** 2016-12-20 15:16 UTC
