### ISSUE TITLE
WIP Scenario: Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by yopasa94** [cucumber/cucumber-js#1668] opened 2021-05-12 15:41 UTC
Hello, 

I've found a issue when I try to run all scenarios (including wip) using dry-run mode. I.E:

This is the feature file, I'm trying to run 

```gherkin
  @blocker @wip
  Scenario: Login to application
    Given Go to the App
    When  I enter user credential
    Then App home should be displayed

 @major @wip
  Scenario: Login using a external app

 @minor @wip
  Scenario: Login using token
```

When I try to run a feature like that I got this error

```
[10:38:10] E/launcher - **Error: TypeError: Cannot read property 'uri' of undefined**
    at parseStep (~node_modules\@cucumber\cucumber\src\formatter\helpers\test_case_attempt_parser.ts:90:27)      
    at ~node_modules\@cucumber\cucumber\src\formatter\helpers\test_case_attempt_parser.ts:169:24
```

I took a look into the code and seems likely the app does not support scenarios without steps.

https://github.com/cucumber/cucumber-js/blob/f37edaadbefea557d87ef5f19bc301a277ac4264/src/formatter/helpers/test_case_attempt_parser.ts#L55

**Comment by davidjgoss** [comment] 2021-06-03 15:35
@yopasa94 I've tried adding an e2e test to reproduce this (see https://github.com/cucumber/cucumber-js/commit/35005591bea61c5cd17fb78c420d89c4bd5d5919) but haven't been able to yet.

Could you confirm a few things:

- Version of cucumber you're running
- Any formatters you're using
- Any other CLI arguments
- Does this only happen with `--dry-run`?

**Comment by AdrianMiska** [comment] 2021-08-31 12:25
We had the same issue and it was caused by a scenario without steps.

**Comment by davidjgoss** [comment] 2021-09-20 23:49
Closing as we have not been able to reproduce this.

**Closed by davidjgoss** 2021-09-20 23:49 UTC
Labels: :bug: bug, :baby_bottle: incomplete
