### ISSUE TITLE
Cannot access the world in a step definition

### ISSUE THREAD

**Issue by iongion** [cucumber/cucumber-js#467] opened 2015-12-04 11:53 UTC
Using _cucumber_ *0.9.2*, My `world.js` (in `test/features/support/world.js`) looks like this:

```
var World = function(callback) {
  var client = null;
  var Request = function() {}
  Request.prototype = {
    setHeaders: function() {
    },
    setMethod: function() {
    },
    setBody: function() {
    }
  }
  var Client = function() {}
  Client.prototype = {
    getRequest: function() {
    }
  }
  this.setupClient = function(clientType) {
    client = new Client();
  }
  this.getClient = function(clientType) {
    client = new Client();
  }
  if (typeof callback === 'function') {
    callback();
  }
};

module.exports = function() {
  this.World = World;
};
```

And a sample step definition:
```
var assert = require('assert');
var _ = require('lodash');
var chai = require('chai');
var expect = chai.expect;
var should = chai.should();

module.exports = function() {
  this.Given(/^I am a "([^"]*)" client$/, function (clientType, callback) {
    this.setupClient(clientType);
    callback();
  });
  this.Given(/^that the request headers are:$/, function (table, callback) {
    // Write code here that turns the phrase above into concrete actions
    // console.log(table)
    //this.getClient().getRequest().setHeaders(table)
    callback();
  });
  this.When(/^I make "([^"]*)" request to "([^"]*)"$/, function (method, path, callback) {
    // Write code here that turns the phrase above into concrete actions
    callback();
  });
  this.Then(/^the response "([^"]*)" should equal:$/, function (arg1, string, callback) {
    // Write code here that turns the phrase above into concrete actions
    callback();
  });
};
```
The problem that I encounter is that `this.setupClient` is `undefined`.
What am I missing ?

If I am changing the step definition by adding:
```
module.exports = function() {
  var worldPath = path.join(config.paths.root, 'test/features/support/world')
  this.World = require(worldPath).World;
  ...
}
```
as found in this [Tutorial](http://custardbelly.com/blog/blog-posts/2014/01/22/cucumberjs-world/), then I receive an error:
```
W:\Workspace\CJSProject\node_modules\cucumber\lib\cucumber\support_code\library.js:95
      var world = new World();
                  ^
TypeError: undefined is not a function
```

**Comment by charlierudolph** [comment] 2015-12-04 16:52
Everything in the initial setup looks correct. Can you provide a bit more detail so I can try to reproduce? (directory structure, sample feature, how you are running cucumber-js). 

When you updated to use
```
module.exports = function() {
  var worldPath = path.join(config.paths.root, 'test/features/support/world')
  this.World = require(worldPath).World;
  ...
}
```
You would also need to change the exports of `test/features/support/world.js` from
```
module.exports = function() {
  this.World = World;
};
```
to 
```
module.exports.World = World;
```

**Comment by charlierudolph** [comment] 2015-12-12 17:29
@iongion any update on this?

**Comment by iongion** [comment] 2015-12-13 15:34
In the documentation on the github index:

```
module.exports = function () {
  this.Given(/^I am on the Cucumber.js GitHub repository$/, function (callback) {
    // Express the regexp above with the code you wish you had.
    // `this` is set to a World instance.
    // i.e. you may use this.browser to execute the step:

    this.visit('https://github.com/cucumber/cucumber-js', callback);

    // The callback is passed to visit() so that when the job's finished, the next step can
    // be executed by Cucumber.
  });

  this.When(/^I go to the README file$/, function (callback) {
    // Express the regexp above with the code you wish you had. Call callback() at the end
    // of the step, or callback.pending() if the step is not yet implemented:

    callback.pending();
  });

  this.Then(/^I should see "(.*)" as the page title$/, function (title, callback) {
    // matching groups are passed as parameters to the step definition

    var pageTitle = this.browser.text('title');
    if (title === pageTitle) {
      callback();
    } else {
      callback(new Error("Expected to be on page with title " + title));
    }
  });
};
```

You see, the this.World loading is not present there so how come this.visit works ?

**Comment by charlierudolph** [comment] 2015-12-13 16:00
That part assumes the world definition from the previous section

**Comment by iongion** [comment] 2015-12-13 16:08
I understand and totally believe you, but you have to also believe me that is the part that confused me :) - I am old :+1: 

Feel free to close this ticket and do whatever you consider necessary and thank you for the patience!

**Comment by jomaora** [comment] 2016-01-19 16:39
@charlierudolph hey, I'm actually having the same problem with world.js in a really silly scenario.

```
module.exports = function () {
    var worldPath = '../support/world';
    this.World = require(worldPath).World;

    this.Given(/^I am connected as an anonymous user$/, (callback) => {
        console.log(this.World, this.World.toString());
        console.log('>>>>>>>', this.api, this.World.api);
        this.test();    
        callback();
    });
};
```
having this as my world.js file:

```
function World() {
    this.api = 'http://localhost:3000';
    this.test = function() {
        console.log('TEEEEEEEST');
    }
}

module.exports.World = World;
```
and neither this.api nor this.test are defined. I have made changes inspired in what you said in your first answer, but nothing seems to change.

```
[jmortega@mbp ~/workspace/orange/dockerization (master)]$ make test-func 
Feature: Products

  As a user of the CloudPro
  I want to get information about the products in the database

  Scenario: Listing all products                                       # features/products.feature:5
[Function: World] 'function World() {\n    this.api = \'http://localhost:3000\';\n    this.test = function() {\n        console.log(\'TEEEEEEEST\');\n    }\n}'
>>>>>>> undefined undefined
    Given I am connected as an anonymous user                          # features/step_definitions/product.js:21
      TypeError: this.test is not a function
          at World.<anonymous> (/sample-api/api/features/step_definitions/product.js:24:14)
    When I request all products                                        # features/step_definitions/product.js:29
    Then I should receive an object matching getProductResponse schema # features/step_definitions/product.js:50
```

any advice?

**Comment by charlierudolph** [comment] 2016-01-19 16:49
I believe the problem is that you are using a fat arrow in your step definition. With the fat arrow you are controlling `this` for the step definition, instead of allowing the caller to set it.

**Comment by jomaora** [comment] 2016-01-19 17:19
@charlierudolph right, indeed writing the test without using an arrow function worked. Thanks.

However it forces me to not use a ES6 syntax. Are you thinking to allow this in a further version, or it will be a won't fix (if it could be consider as a bug)?

**Comment by charlierudolph** [comment] 2016-01-19 17:55
Part of the arrow functions in ES6 is the context binding. We don't want the context binding here, so I don't think the fat arrow makes sense. After some experimentation, I can't find any way to override the context of a function created with a fat arrow.

**Closed** 2016-01-25 16:42 UTC
