### ISSUE TITLE
Steps undefined when using cucumber-js CLI

### ISSUE THREAD

**Issue by marius1706** [cucumber/cucumber-js#1278] opened 2020-01-25 14:45 UTC
Hi, 

I'm using cucumber-js CLI in an azure function like this:

       let runArgs = ['node', 'cucumber-js'].concat(['--tags', '@ttcid:' + templateTestCaseId])
    context.log("Run test : " + testId);
  
       let outputStream = new stream.Writable();

       outputStream._write = async function (chunk, encoding, done) {
            context.log(chunk.toString());
            done();
      };
    
      const cli = new Cli({argv: runArgs, cwd: process.cwd(), stdout: outputStream});
      if (!library) {
           const config = await cli.getConfiguration();
           library = cli.getSupportCodeLibrary(config);
      }
     cli.getSupportCodeLibrary = () => library;

    try {
            let resultOfTest = await cli.run();
            context.log("Result of running tests: " + JSON.stringify(resultOfTest));
         } catch (e) {
               context.log("Running tests were failed: " + e.stack);
         }

Multiple sequential requests are made to that azure function from other application for running different tests.

The problem is,  for some calls, I'm getting undefined steps, even if I'm using the solution from this issue https://github.com/cucumber/cucumber-js/issues/786 where library value is cached and reused.

When that happened, arrays afterTestCaseHookDefinitions, afterTestRunHookDefinitions,....stepDefinitions from library object are empty.

Can you please help me with a solution for this ? 

Thank you!

**Comment by charlierudolph** [comment] 2020-01-29 16:38
What version of cucumber-js are you using? And why do you need to overwrite Cli's `getSupportCodeLibrary` method?

Its hard to tell if this is an issue with cucumber vs some other part of your workflow. If you can create a minimum reproducible example, I can try to help debug

**Comment by marius1706** [comment] 2020-01-30 11:05
Hi @charlierudolph ,

Thanks for the answer.

I'm using version 6.0.5.

I'm overwriting getSupportCodeLibrary because I want to return that library value from first run when stepDefinitions are populated as on next runs, that is empty;

I created a simple example when that is reproducing:
https://github.com/marius1706/cucumber-js-cli

You need to run that `runTest.js` .

I simulated the  azure function calls by using a for loop and call that `runCucTest` where that CLI is instantiated.

You'll see that on first run, test was run and passed; on second run `Undefined. Implement with the following snippet:` is displayed.

This is the console output:

```
"C:\Program Files\nodejs\node.exe" D:\cucumber-js-cli\azure-function\run_test\runTest.js
....

1 scenario (1 passed)
4 steps (4 passed)
0m00.001s
Result of running tests: {"shouldExitImmediately":false,"success":true}
UUUU

Warnings:

1) Scenario: Addition of two numbers # features\sum.feature:4
   ? Given I have first number 6
       Undefined. Implement with the following snippet:

         Given('I have first number {int}', function (int) {
         // Given('I have first number {float}', function (float) {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });

   ? And I have second number 4
       Undefined. Implement with the following snippet:

         Given('I have second number {int}', function (int) {
         // Given('I have second number {float}', function (float) {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });

   ? When I make the sum of those two numbers
       Undefined. Implement with the following snippet:

         When('I make the sum of those two numbers', function () {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });

   ? Then result should be 10
       Undefined. Implement with the following snippet:

         Then('result should be {int}', function (int) {
         // Then('result should be {float}', function (float) {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });


1 scenario (1 undefined)
4 steps (4 undefined)
0m00.000s
Result of running tests: {"shouldExitImmediately":false,"success":false}

Process finished with exit code 0
```

**Comment by charlierudolph** [comment] 2020-01-31 06:33
Okay. Yep, so this is currently due to this line which clears the support code library: https://github.com/cucumber/cucumber-js/blob/v6.0.5/src/cli/index.js#L74.

The support files are not reloaded as expected because node caches requires and thus will not re-execute the file. You could clear the cache: https://nodejs.org/api/modules.html#modules_require_cache

If you want to share the library between runs, I would expect the solution from the other issue would work (though is definitely a hack).

Can you expand on your use case here as to why you want to use the cli node API in this way? Feels like we need something between the cli and runtime classes to make the node API easier to use

**Comment by marius1706** [comment] 2020-02-04 13:13
Hi @charlierudolph ,

Thanks for your answer.

I tried to clear node cache like this:

```
        let originalKeys = Object.keys(require.cache);
        let resultOfTest = await cli.run();
        let newKeys = Object.keys(require.cache);
        while (newKeys.length > originalKeys.length) {
            delete require.cache[newKeys.pop()];
        }
```
I still encountered that undefined randomly and rare.

I'm using cli node API in this way because I'm using an azure function which will be called from other application for different tests.

In the other application I'm collecting data which I need in test and send that data to azure function(API call) where I'm calling that CLI with the data as arguments for running the test;

I'm using an After hook where I'm updating the status of the test in that external application.

**Comment by jbdoster** [comment] 2020-09-03 00:15
Is there a fix for this without clearing node cache?

**Comment by mattwynne** [comment] 2021-07-15 21:25
#1711 is related

**Comment by davidjgoss** [comment] 2021-09-20 23:44
Closing this now, effectively as a duplicate, as we'll be addressing the use case in #1711 - the support code library will be reusable in subsequent runs in the same process.

**Closed by davidjgoss** 2021-09-20 23:44 UTC
Labels: :pray: help wanted, :bug: bug

**Comment by OhadR** [comment] 2022-02-01 10:31
this issue should not be closed, as this problem is reproducible.

my use case is to trigger cucumber several times, using its Cli.

i have spent HOURS on this, trying to run cucumber by its Cli. After struggling, I have noticed that it can be invoked only once, and in the second run it does not find the step-definitions (because of SupportCodeLibraryBuilder - nodejs cache the step-definitions so in the 2nd run it does not "require" them again, in getSupportCodeLibrary()

**Comment by aurelien-reeves** [comment] 2022-02-01 14:29
The development done as part of #1711 will provide a proper way to programmatically run cucumber several times. It will then provide a nice workaround for your issue.

The CLI, as the name suggest, is not designed to be use programmatically, but as a CLI.

To automate cucumber runs programmatically, please refer to #1711.

**Comment by adnanerlansyah505** [comment] 2024-04-02 04:43
> Hi @charlierudolph ,
> 
> Thanks for your answer.
> 
> I tried to clear node cache like this:
> 
> ```
>         let originalKeys = Object.keys(require.cache);
>         let resultOfTest = await cli.run();
>         let newKeys = Object.keys(require.cache);
>         while (newKeys.length > originalKeys.length) {
>             delete require.cache[newKeys.pop()];
>         }
> ```
> 
> I still encountered that undefined randomly and rare.
> 
> I'm using cli node API in this way because I'm using an azure function which will be called from other application for different tests.
> 
> In the other application I'm collecting data which I need in test and send that data to azure function(API call) where I'm calling that CLI with the data as arguments for running the test;
> 
> I'm using an After hook where I'm updating the status of the test in that external application.

Where you put that code in the project? is it on wdio config or make separate file for it?
