### ISSUE TITLE
Empty .feature files cause Cucumber.js to stop

### ISSUE THREAD

**Issue by amazingsam** [cucumber/cucumber-js#375] opened 2015-07-25 12:30 UTC
**Impact**
Extremely Low

**Error**
````
$ cucumber.js --coffee
/usr/local/lib/node_modules/cucumber/lib/cucumber/parser.js:20
          throw e;
                ^
TypeError: Cannot read property 'convertScenarioOutlinesToScenarios' of undefined
path: /path/to/project/features/empty.feature
    at Object.finish (/usr/local/lib/node_modules/cucumber/lib/cucumber/ast/assembler.js:105:31)
    at Object.handleEof [as eof] (/usr/local/lib/node_modules/cucumber/lib/cucumber/parser.js:67:20)
    at Lexer.scan (/usr/local/lib/node_modules/cucumber/node_modules/gherkin/lib/gherkin/lexer/en.js:1049:21)
    at GherkinLexer.scan (/usr/local/lib/node_modules/cucumber/lib/cucumber/gherkin_lexer.js:24:11)
    at Object.parse (/usr/local/lib/node_modules/cucumber/lib/cucumber/parser.js:17:17)
    at Object.getFeatures (/usr/local/lib/node_modules/cucumber/lib/cucumber/runtime.js:37:35)
    at Object.start (/usr/local/lib/node_modules/cucumber/lib/cucumber/runtime.js:16:37)
    at Object.runSuiteWithConfiguration (/usr/local/lib/node_modules/cucumber/lib/cucumber/cli.js:19:15)
    at Object.run (/usr/local/lib/node_modules/cucumber/lib/cucumber/cli.js:12:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/cucumber/bin/cucumber.js:4:5)
````
**System**
Darwin 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

**Replicate**
Create an empty .feature file, run cucumber.js and it will throw this error.

**Quick fix**
Remove the empty .feature file or put some dummy lines in there.

**Suggestion**
A more graceful warning, ignoring the empty file(s) and continue.

**Comment by charlierudolph** [comment] 2015-09-28 16:28
Duplicate of #306 which was fixed in 373d6c6b2df6f18ba3bce9048603d18f9434039c

**Closed by charlierudolph** 2015-09-28 16:28 UTC
