### ISSUE TITLE
step ambiguity issue

### ISSUE THREAD

**Issue by tony-kerz** [cucumber/cucumber-js#847] opened 2017-06-06 15:47 UTC
the following step definitions:
```
    When('we HTTP GET "{path}"', async function(path) {
      //...
    })

    When('we HTTP GET "{path}" with query "{query}"', async function(path, query) {
      //...
    })
```
incurs the following: 
```
1) Scenario: index with query - test/features/test.feature:23
   Step: When we HTTP GET "/" with query "_id=2" - test/features/test.feature:24
   Message:
     Multiple step definitions match:
       we HTTP GET "{path}"                      - src/index.js:41
       we HTTP GET "{path}" with query "{query}" - src/index.js:45
```
should there be implied begin-end terminators in these expressions?

**Comment by aslakhellesoy** [comment] 2017-06-06 18:52
Dupe of cucumber/cucumber-expressions-javascript#5

**Closed by aslakhellesoy** 2017-06-06 18:52 UTC
