### ISSUE TITLE
RegEx \d passing down a string instead of a number

### ISSUE THREAD

**Issue by Sawtaytoes** [cucumber/cucumber-js#649] opened 2016-10-01 04:50 UTC
When I use Cucumberjs and setup a module, I have to manually set all my RegEx digits to a JavaScript type 'number' using `Number(value)`. I would assume using `\d` would return me a number, not a string.

```js
this.Given(/^a number (\d+)$/, (num, next) => {
    num = Number(num);
    mathy = new Mathy({ value: num });

    assert.equal(mathy.get(), num,
        "Initial value isn't set properly."
    );
    assert.equal(typeof mathy.get(), 'number',
        "Value is a string, not a number."
    );

    next().pending();
});
```

Even though my `Mathy` module is just a test, I can imagine having many modules that require numbers passed in, not strings. Would it be possible that if I have `\d` in my RegEx, it sets the type to a number instead of a string?

**Comment by aslakhellesoy** [comment] 2016-10-01 07:17
This is a dupe of #622

**Closed by aslakhellesoy** 2016-10-01 07:17 UTC
