### ISSUE TITLE
Cucumber not wating for promises

### ISSUE THREAD

**Issue by axelbarfod** [cucumber/cucumber-js#974] opened 2017-11-09 13:09 UTC
Hi, i'm having the following problem. In one of my steps I need to a navigate into a url. This URL takes a parameter which is generated by doing a request to another URL and when this request is do it returns an ID. This ID is needed so I can add it to the URL to then navigate. 
So what I am doing is I make this request to retrieve my Id and inside the promise I navigate to the desired url but when I run the test the promise is executed and then it moves to another step and the test fails because the URL is wrongly formed. Below is my code:

```
`Given(/^I make a post request and retreive the Id i got the page + id$/, () => {
  //I make the post request 
  var transactionIdPromise = utils.getTransactionId(1);
  var url = "";

  return transactionIdPromise.getBody('utf8').then(JSON.parse).done(function (result) {
      var id = result.transaction_id;
      url = "https://mywebpage.com:8443/" + id;
      client.url(url)
  });
});`
```
Below is the code the returns the transaction id.

`var getTransactionId = function (user) {
        return request('POST', 'http://localhost:8888/internal/retreive_transaction/?', {json: {user_id: user, type: 'UNIQUENESS', info: '{"person_id":"xxxxxxxxxxxxxxxx"}'}});
    };`

Here are my posts on Stackoverflow: [Post 2](https://stackoverflow.com/questions/46960806/nightwatch-not-navigating-to-url/47120142?noredirect=1#comment81296816_47120142) and [Post 1](https://stackoverflow.com/questions/46933353/cucumber-wait-for-promise-to-finish/46939525#46939525)

**Comment by charlierudolph** [comment] 2017-11-09 16:04
I believe the couple posts have it correct that you need to chain the promises. You return a promise and inside `then` blocks you need to also return any generated promises. Thus i believe you need `return client.url(url)`. 

Is a `done` handler the same as another `then` or is that something different?

**Comment by axelbarfod** [comment] 2017-11-09 18:58
I already tried doing:
`Given(/^I make a post request and retreive the Id i got the page + id$/, () => {
  //I make the post request 
  var transactionIdPromise = utils.getTransactionId(1);
  var url = "";

  return transactionIdPromise.getBody('utf8').then(JSON.parse).done(function (result) {
      var id = result.transaction_id;
      url = "https://mywebpage.com:8443/" + id;
      return client.url(url)
  });
});`

And it's still not waiting for it to finish.

**Comment by charlierudolph** [comment] 2017-11-09 19:14
Is there any difference between`then` vs `done` in whatever promise library you are doing?

**Comment by axelbarfod** [comment] 2017-11-09 23:26
I'm using the  EcmaScript6 promise library  and the framework im using is nightwatch.js

**Comment by charlierudolph** [comment] 2017-11-09 23:32
Can you link documentation for `done`. That is a weird part to me. Maybe try switching that to `then`

**Comment by charlierudolph** [comment] 2017-11-24 14:43
So this error was caused by you thinking you were returning a promise but cucumber was not receiving a promise. I think this has come up a couple times, and wonder if we could add to the output what interface cucumber determined the step was using (synchronous, promise, or callback).

**Comment by charlierudolph** [comment] 2018-01-04 01:27
Closing and will create a new ticket for a debug mode

**Closed by charlierudolph** 2018-01-04 01:27 UTC

**Comment by lenntt** [comment] 2018-05-02 10:24
My guess is cucumber did use the promise interface (as expected), 
but the returned promise resolved too early.

as `done` (not standard JS) behaves differently (https://stackoverflow.com/questions/5436327/jquery-deferreds-and-promises-then-vs-done).
