### ISSUE TITLE
'test_case_attempt_parser' can't handle exceptions in After hooks

### ISSUE THREAD

**Issue by jenimi** [cucumber/cucumber-js#1818] opened 2021-10-15 10:00 UTC
**Describe the bug**
When exception occurs in an After hook the formatter can't handle it properly.

**To Reproduce**
In an After hook throw an exception:
```
After('@TestAfterHook', function () {
  throw("This can't be handled properly");
});
```
**Expected behavior**
If exception occurs in an after hook, it should be properly handled by the formatter and output similar to
```
4) Scenario: Clean up ...
   ✖ After # tests/path/to/hooks.js:111
       This can't be handled properly
   ✔ Before # tests/path/to/hooks.js:111
   ✔ Before # tests/path/to/hooks.js:111
```
Should be displayed in the test report

**Desktop:**
 - OS: Ubuntu 18

**Additional context**
I think the problem lays in the `isBeforeHook` var in `https://github.com/cucumber/cucumber-js/blob/main/src/formatter/helpers/test_case_attempt_parser.ts`
it is determined by
```
    isBeforeHook = isBeforeHook && doesHaveValue(testStep.hookId)
```
but AfterHooks have `testStep.hookId` too, so AfterHooks set isBeforeHook to true, and later on in function parseStep
```
    if (isBeforeHook) {
      hookDefinition = supportCodeLibrary.beforeTestCaseHookDefinitions.find(
        (x) => x.id === testStep.hookId
      )
    } else {
      hookDefinition = supportCodeLibrary.afterTestCaseHookDefinitions.find(
        (x) => x.id === testStep.hookId
      )
    }
```
AfterHooks are searched in `supportCodeLibrary.beforeTestCaseHookDefinitions` and can't be found there

**Comment by davidjgoss** [comment] 2022-06-19 10:43
I'm not able to reproduce this. Are you able to post a minimal repro example repo that shows this?

**Comment by davidjgoss** [comment] 2022-07-19 08:53
Closing as we can't reproduce, but please comment if you have something new on this.

**Closed by davidjgoss** 2022-07-19 08:53 UTC
Labels: :bug: bug, :baby_bottle: incomplete
