### ISSUE TITLE
Cucumber is not able to separate two different string from data table

### ISSUE THREAD

**Issue by dixitgargi** [cucumber/cucumber-js#1078] opened 2018-04-26 17:00 UTC
> **Description**: Login Window contain 3 main objects "username"(textbox) , "password"(textbox) and "login"(button)

> **Observation**: when running test, in username text box it is entering testtest(i.e. entering value of password in the same editbox) 

> Could you please help me with this issue as it is breaking basic functionality and it is a blocker for me to automate?

> Feature file:
```
@login
Feature: Login
    Scenario Outline: Login
    Given I launch url 
    Then I enter <username>
    Then I enter password <password>
    Then I click on login button
    Then I verify login screen
    Then I click on logOut
    Examples: 
     | username | password   |
     | test           | test        | 
```

> StepDefinetion
```
Given(/^I launch webapp url$/, function () {
    return browser.get('https://xyz.com');
    });
Then(/^I enter (.*)$/, function (username) {
        const Login = new loginPage();
        return Login.enterUserName(username);
    });
Then(/^I enter password (password)$/, function (password) {
        const Login = new loginPage();
        return Login.enterPassword(password);
        console.log('pass');
    }); 
```

**Comment by charlierudolph** [comment] 2018-04-26 18:30
Based on your post, I have no idea what the issue is. In the step definitions, the username parameter should be "test" and the password parameter should be "test". Can you confirm if that is the case? If so, the issue is not in cucumber.

**Comment by dixitgargi** [comment] 2018-04-27 01:55
Yes username and password should be treated as diffrent entity.
But while executing cucumber enters both the value in username field
Although there are two diffrent function for username field and password field

**Comment by aslakhellesoy** [comment] 2018-05-30 14:09
Can we close this?

**Comment by dixitgargi** [comment] 2018-07-12 08:16
Yes this issue is resolved now we can close this

**Closed** 2018-07-13 02:21 UTC
