### ISSUE TITLE
Run specific scenario in v3

### ISSUE THREAD

**Issue by mmuller99** [cucumber/cucumber-js#924] opened 2017-09-05 11:31 UTC
Hi there,

Since v3 you are unable to run a specific scenario within a feature file. It will run all the scenarios.

ex. helloworld.feature:46

Thanks,
Marco

**Comment by charlierudolph** [comment] 2017-09-05 14:35
We have features to verify this is working: https://github.com/cucumber/cucumber-js/blob/v3.0.1/features/target_specific_scenarios_by_line.feature (and I just verified it still works on cucumber-js own test suite). Any more detail on the matter you can give? (sample project structure and the full command you ran) If you supply a file and line, it should not run all scenarios. It should be running just the matching scenarios (or none if nothing matches).

**Comment by mmuller99** [comment] 2017-09-08 07:34
Hi Charlie,

Please find attached test project
[test-cucumber.zip](https://github.com/cucumber/cucumber-js/files/1287067/test-cucumber.zip)

Am running Windows 10, using zsh, but same happens in PS.

![](http://g.recordit.co/fArmbV7Ee4.gif)

**Comment by mmuller99** [comment] 2017-09-08 08:04
Running the https://github.com/cucumber/cucumber-js/blob/v3.0.1/features/target_specific_scenarios_by_line.feature tests pass

**Comment by charlierudolph** [comment] 2017-09-23 20:51
Downloaded your test project and it works for me (on a Mac). We have appveyor CI and are able to run cucumber there and the same test.

This is very odd. Sorry I don't think I can be of much help here. Its especially odd if that test passes for you locally but then this isn't working properly. 

Could you possibly debug further by adding some console.log statements to the installed node module? Some places to look at printing out the argv passed to `cli/argv_parser` and what feature paths are passed to the `pickle_filter`

**Comment by mmuller99** [comment] 2017-10-02 12:28
Found the issue. Running in PS:

The featureUriToLinesMapping object has the paths exactly as what is being passed when running the tests:

featureUriToLinesMapping: `{ '.\features\bar.feature': [ 3 ] }`

where the pickle filters uri has been normalized to:

uri: `features\bar.feature`

Thus not matching on `this.featureUriToLinesMapping[uri];`

![](http://g.recordit.co/AdY7mmIXr1.gif)

**Comment by mmuller99** [comment] 2017-10-02 12:56
Also in cygwin, the pickle filter is normalizing the path to Windows format instead of UNIX:

featureUriToLinesMapping: { 'features/bar.feature': [ 3 ] }
uri: `features\bar.feature`

**Comment by gd46** [comment] 2017-10-16 01:30
@charlierudolph I was having a similar issue with getting this feature to run a specific scenario by line number. Im working on Mac, and I have this project setup: 

https://github.com/gd46/dibellag-automation-framework 

You can try running an example with: 

```
npm test -- --browserName chrome --specs test/features/cucumber/transform.feature:14
```

And I am still seeing all scenarios in the feature being executed.

**Comment by charlierudolph** [comment] 2017-10-16 02:54
@gd46 Taking a quick look at your example in appears your framework uses `--features` not ``-specs`

**Comment by gd46** [comment] 2017-10-16 21:27
I did it that way because of how in trying to sort out the parallel execution. But passing specs works for regular execution but if I pass a file with a number I see it execute all scenarios in that file.

**Comment by gd46** [comment] 2017-10-16 22:46
From what I can tell so far it appears that this line: 

https://github.com/cucumber/cucumber-js/blob/master/src/cli/index.js#L67

Returns featurePaths as absolute paths. So if I write my specs as: 

```
test/features/cucumber/transform.feature:14
```
or
```
./test/features/cucumber/transform.feature:14
```
It comes out to be: 
```
/Users/dibellag/dibellag-automation-framework/test/features/cucumber/transform.feature
```

Which doesnt allow the run spec file line number to work for me.

**Comment by charlierudolph** [comment] 2017-10-16 23:41
@gd46 The configuration builder expands the feature paths in order to read the files but the unexpanded paths are kept for the filter options. https://github.com/cucumber/cucumber-js/blob/master/src/cli/configuration_builder.js#L47

**Comment by gd46** [comment] 2017-10-17 21:21
Hmmm ok. Do you think the issue is in protractor? I see inside protractor cucumber framework index.js exports.run spec is the absolute path.

**Comment by gd46** [comment] 2017-10-17 23:27
@charlierudolph I tried what @mmuller99 was talking about in regards to featureUriToLinesMapping. In my case I do not see it matching because it contains the absolute path and its comparing it against the relative path of the spec.

**Comment by gd46** [comment] 2017-10-18 01:19
@charlierudolph I am able to test my example if I update this line: 

https://github.com/cucumber/cucumber-js/blob/master/src/pickle_filter.js#L50

to the following: 

```
let path = require('path')
 const lines = this.featureUriToLinesMapping[path.resolve(uri)]
```

This was my short hack to see it working within my test setup.

**Comment by mmuller99** [comment] 2017-10-18 09:47
I had to do a `path.normalize` on both `getFeatureUriToLinesMapping` and `matchesAnyLine` to get both my scenario as well as the cucumber-js lib tests to pass.  Not pretty, just a quick test

pickle_filter.js

```javascript
import _ from 'lodash'
import path from 'path'
import { TagExpressionParser } from 'cucumber-tag-expressions'

const FEATURE_LINENUM_REGEXP = /^(.*?)((?::[\d]+)+)?$/
const tagExpressionParser = new TagExpressionParser()

export default class PickleFilter {
  constructor({ featurePaths, names, tagExpression }) {
    this.featureUriToLinesMapping = this.getFeatureUriToLinesMapping(
      featurePaths || []
    )
    this.names = names || []
    if (tagExpression) {
      this.tagExpressionNode = tagExpressionParser.parse(tagExpression || '')
    }
  }

  getFeatureUriToLinesMapping(featurePaths) {
    const mapping = {}
    featurePaths.forEach(featurePath => {
      const match = FEATURE_LINENUM_REGEXP.exec(featurePath)
      if (match) {
        const uri = path.normalize(match[1])
        const linesExpression = match[2]
        if (linesExpression) {
          if (!mapping[uri]) {
            mapping[uri] = []
          }
          linesExpression
            .slice(1)
            .split(':')
            .forEach(function(line) {
              mapping[uri].push(parseInt(line))
            })
        }
      }
    })
    return mapping
  }

  matches({ pickle, uri }) {
    return (
      this.matchesAnyLine({ pickle, uri }) &&
      this.matchesAnyName(pickle) &&
      this.matchesAllTagExpressions(pickle)
    )
  }

  matchesAnyLine({ pickle, uri }) {
    const lines = this.featureUriToLinesMapping[path.normalize(uri || '')]
    if (lines) {
      return _.size(_.intersection(lines, _.map(pickle.locations, 'line'))) > 0
    } else {
      return true
    }
  }

  matchesAnyName(pickle) {
    if (this.names.length === 0) {
      return true
    }
    return _.some(this.names, function(name) {
      return pickle.name.match(name)
    })
  }

  matchesAllTagExpressions(pickle) {
    if (!this.tagExpressionNode) {
      return true
    }
    return this.tagExpressionNode.evaluate(_.map(pickle.tags, 'name'))
  }
}
```

**Comment by gd46** [comment] 2017-10-18 12:20
@mmuller99 Thanks for your findings, I was trying to resolve why this wasnt working for me a couple weeks ago when I realized your findings was a similar issue to mine. I think we need to do more than just path.normalize or path.resolve. I think the end solution should do both, because in the case where the spec path input is absolute we are always trying to compare it with a relative path. I think these two should be normalized to be the same and then use path.normalize to make sure its windows safe. Thoughts?

**Comment by mmuller99** [comment] 2017-10-18 12:40
@gd46 Thanks for your input.  The normalize won't be necessary if we are always going to use absolutes, as the paths will get normalized internally during the `path.resolve` call.

**Comment by gd46** [comment] 2017-10-18 20:37
I see, thanks @mmuller99. @charlierudolph What are your thoughts on doing a path.resolve on both the input spec path and the sourceLocation uri when doing these comparisons to make sure there always accurate?

**Comment by gd46** [comment] 2017-10-18 21:56
I see it work correctly on my end if I update your path.normalize to path.resolve. This should resolve the Windows path issue, and the comparing absolute path to relative path issue. I think we should probably add more tests here: 

https://github.com/cucumber/cucumber-js/blob/master/src/pickle_filter_spec.js

In order to capture these scenarios.

**Comment by mmuller99** [comment] 2017-10-23 21:08
@charlierudolph any thoughts?

**Comment by charlierudolph** [comment] 2017-10-23 21:33
I'm good with using `path.resolve` in both places

**Comment by gd46** [comment] 2017-10-23 21:49
Great @mmuller99 would you like to create the PR since you found the issue? Otherwise I can create one if you need.

**Comment by mmuller99** [comment] 2017-10-23 21:54
@gd64 I'll add the PR, is there any specific test scenario we need to look at?

**Comment by charlierudolph** [comment] 2017-10-23 21:56
If you can create a failing test in pickle_filter_spec that is fixed by using path.resolve that would be great

**Closed** 2017-10-24 15:59 UTC
