### ISSUE TITLE
Add option to allow generating snippets without callbacks

### ISSUE THREAD

**Issue by tooky** [cucumber/cucumber-js#525] opened 2016-03-01 09:54 UTC
When you are writing mostly promise based steps, it would be useful if we could set an option to generate step definitions without a callback parameter.

(I'd like to have a go at doing this to learn more about cucumber.js, but if someone else beats me to it, I won't mind.)

**Comment by aslakhellesoy** [comment] 2016-03-01 10:00
Dupe of #524 ;-)

**Closed by aslakhellesoy** 2016-03-01 10:00 UTC
Labels: feature-request
