### ISSUE TITLE
--no-strict flag has no effect when using cucumber.js file and --profile

### ISSUE THREAD

**Issue by ggarcia24** [cucumber/cucumber-js#1665] opened 2021-05-04 14:05 UTC
Hello, first of all thank you very much for porting this tool to javascript! I've found an issue with the --profile flag, I've followed the 10 minutes guide for cucumber-js (https://cucumber.io/docs/guides/10-minute-tutorial/), I've modified some things from the tutorial to run in the following way:

Directory structure:

```
|- features
    |- is_it_friday_yet.feature
| -src
    |- step_definitions
        |- stepdefs.js
    |- support
        |- hooks.js
        |- custom_parameters.js
        |- world.js
|- README.md
|- cucumber.js
```

```js
// cucumber.js
onst DEFAULT_OPTIONS = [
  '--no-strict',
  '--require src/support/hooks.js',
  '--require src/support/custom_parameters.js',
  '--require src/support/world.js',
  '--require src/step_definitions/**/*.js',
  '--publish-quiet',
];

const cliOpts = DEFAULT_OPTIONS.join(' ');

module.exports = {
  // The default is only run on dev machines
  default: `${cliOpts} --format progress-bar --format-options '{"snippetInterface": "synchronous"}' --tags @wip`,
  all: `${cliOpts} --format message:output/cucumber-messages.ndjson --retry 3 --retry-tag-filter @flacky`,
}
```

```js
// stepdefs.js

const { Given, When, Then } = require('@cucumber/cucumber');

Given('today is Sunday', function () {
  // Write code here that turns the phrase above into concrete 
  return 'pending';
});

When('I ask whether it\'s Friday yet', function () {
  // Write code here that turns the phrase above into concrete actions
  return 'pending';
});

Then('I should be told {string}', function (string) {
  // Write code here that turns the phrase above into concrete actions
  return 'pending';
});
```

Running the command line with `--profile all` returns error code 1 when it shouldn't 
```
$ cucumber-js --profile all
...

$ echo $?
1
```

But if I expand the command line to include all the information included in the profile everything works file
```
$ cucumber-js --no-strict --require src/support/hooks.js --require src/support/custom_parameters.js --require src/support/world.js --require "src/step_definitions/**/*.js" --publish-quiet --format message:output/cucumber-messages.ndjson --retry 3 --retry-tag-filter @flacky


$ echo $?
0
```

I'm currently investigating if I can solve the issue, hope to create a PR.

Best regards
Gonzalo

**Comment by charlierudolph** [comment] 2021-06-04 05:03
Hi @ggarcia24,

I was unable to reproduce and --no-strict was working properly for me in the profile and as a CLI argument. Maybe there was something else leading to the failure.

I'm going to close this for now but feel free to comment if you are still experiencing this and we can reopen

**Closed by charlierudolph** 2021-06-04 05:03 UTC
