### ISSUE TITLE
testCase does not contain Scenario name

### ISSUE THREAD

**Issue by paul-phillips-ark** [cucumber/cucumber-js#943] opened 2017-10-05 14:32 UTC
When using 2.0.0, I used ScenarioResult to get the status of the test scenario and also the name of the current scenario. This was useful as I had a conditional statement on failure to take a screenshot and name it after the failed scenario, making it easy to see exactly where each scenario was falling. #919, I believe was used to 'fix' ScenarioResult as it was no longer functioning in more recent versions of Cucumber-js. I am now using V 3.0.3 as testCase gives me a similar function as ScenarioResult. However, unlike ScenarioResult, it does not contain the scenario name in the object (it does contain the status of the test though, at least). Is there a new method to get the name of the scenario? At the moment it seems to only give the name of the feature file this failure comes from, which is not specific enough for my needs. Thanks in advance :)

**Comment by charlierudolph** [comment] 2017-10-05 14:59
Closing as duplicate of #923, there is no way to get the name at the moment.

**Closed by charlierudolph** 2017-10-05 14:59 UTC

**Comment by paul-phillips-ark** [comment] 2017-10-05 15:08
My bad. Will use the uri and line features.
