### ISSUE TITLE
Tags for examples in scenario outlines is not supported

### ISSUE THREAD

**Issue by yopasa94** [cucumber/cucumber-js#1642] opened 2021-04-15 19:29 UTC
Cucumber Version: 7.0.1
Node Version: 14.14.31
Operating System: Win 10

Scenario Outline: Sample test case
Given this is a test case
When I have the following data table
| <scenario_example> |
Then a JSON report will be generated

@critical
Examples:
| scenario_example |
| Test Child Tag 1 |

@blocker
Examples:
| scenario_example |
| Test Child Tag 2 |

When I run the test case above with the tag: "--tags @critical" and "-f json:reports/cucumber-report.json", the test case runs successfully, but the following error is thrown:
``[chrome #01]
[chrome #01] 8 scenarios (8 passed)
[chrome #01] 48 steps (48 passed)
[chrome #01] 2m58.724s (executing steps: 2m58.252s)
[chrome #01] [14:22:34] I/runnerCli - Cannot read property 'location' of undefined

[14:22:34] I/testLogger -

[14:22:34] E/launcher - Runner process exited unexpectedly with error code: 1
[14:22:34] I/launcher - 0 instance(s) of WebDriver still running`
`
Is there any way to support tag at the example level (it was supported in the past )? why was that feature removed ?
![image](https://user-images.githubusercontent.com/22714699/114927341-f7cf3680-9df6-11eb-8786-21003cdd73b1.png)

**Comment by charlierudolph** [comment] 2021-04-15 19:46
We have this [feature](https://github.com/cucumber/cucumber-js/blob/master/features/target_specific_scenarios_by_tag.feature) that should be validating this is working. I'm not sure why all out examples are verify it failing though. Let me review that feature. 

In the mean time can you provide a more complete example of what you are running? (ie a repo with the source and the exact command to run to reproduce the error). Based on the sample output it appears you are not running just basic cucumber-js

**Comment by charlierudolph** [comment] 2021-04-15 19:51
Okay reviewing the feature, it appears the issue is the JSON formatter. Going to close this as a duplicate of #1621

**Closed by charlierudolph** 2021-04-15 19:51 UTC
