### ISSUE TITLE
Cucumber runs two test cases simultaneously after failing one.

### ISSUE THREAD

**Issue by richardmcsong** [cucumber/cucumber-js#371] opened 2015-07-14 15:50 UTC
So I have a few test cases, and the first one is failing the Given step.
It reports the failed Given step, and then invokes the next two scenarios at once. 
```
 Scenario: First Login User Agreement Dialog elements    # features/Whiteglove/login.feature:16
    Given "User Agreement" dialog is shown on first login # features/Whiteglove/login.feature:17
      AssertionError: User Agreement dialog does not exist.
        at WebdriverIO.<anonymous> (/home/deploy/test/features/step_definitions/login.js:87:24)
        at /home/deploy/test/node_modules/webdriverio/lib/utils/PromiseHandler.js:85:52
        at process._tickDomainCallback (node.js:486:13)

    Then the app shows "Terms of Use" link                # features/Whiteglove/login.feature:18
    Then the app shows "Privacy Policy" link              # features/Whiteglove/login.feature:19
    Then the app shows "I Accept" button                  # features/Whiteglove/login.feature:20
    Then the app shows "I Decline" button                 # features/Whiteglove/login.feature:21
    Given "User Agreement" dialog is shown on first login # features/Whiteglove/login.feature:17


  Scenario: First Login User Agreement Decline                      # features/Whiteglove/login.feature:23


  Scenario: Org Admin login                                   # features/Whiteglove/login.feature:28
    Before
      RuntimeError: RuntimeError
           (UnknownError:13) An unknown server-side error occurred while processing the command.
           Problem: POST /session//elements
      Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
      System info: host: 'qa01', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-504.16.2.el6.x86_64', java.version: '1.8.0_45'
      Driver info: driver.version: unknown

           Callstack:
           -> elements("input[name=\"username\"]")
           -> setValue("input[name=\"username\"]","keystrokes")

    Given Login page is shown                                 # features/Whiteglove/login.feature:29
    When I login as an org admin                              # features/Whiteglove/login.feature:30
    Then the app shows "title" as the title # features/Whiteglove/login.feature:31
    Then the app shows "User Agreement" dialog                # features/Whiteglove/login.feature:32
    Given "User Agreement" dialog is shown on first login     # features/Whiteglove/login.feature:24
      RuntimeError: RuntimeError
           (UnknownError:13) An unknown server-side error occurred while processing the command.
           Problem: POST /session//elements
      Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
      System info: host: 'qa01', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-504.16.2.el6.x86_64', java.version: '1.8.0_45'
      Driver info: driver.version: unknown

           Callstack:
           -> elements("input[name=\"username\"]")
           -> setValue("input[name=\"username\"]","keystrokes")

    When I click "I Decline" button                           # features/Whiteglove/login.feature:25
    Then the app shows "title" as the title# features/Whiteglove/login.feature:26
```

The first test case was intentionally failed (using the Given), as when I run this the user is no longer on first login. Notice that the First Login User Agreement Decline and the Org Admin login test cases have their Cucumber steps intertwined with each other. Also notice that the failed Given is run again after the whole test case again... when the feature file doesn't have it. The failed Given has a green status when the step is run again (which means it passed? but it didn't!)

The Selenium server has this to say about it:
```
11:44:23.206 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
11:44:23.217 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
11:44:25.774 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]]
11:44:25.788 INFO - Executing: [maximise window])
11:44:25.869 INFO - Done: [maximise window]
11:44:25.875 INFO - Executing: [get: https://localhost:5143/])
11:44:27.724 INFO - Done: [get: https://localhost:5143/]
11:44:27.737 INFO - Executing: [find elements: By.cssSelector: input[name="username"]])
11:44:27.844 INFO - Done: [find elements: By.cssSelector: input[name="username"]]
11:44:27.851 INFO - Executing: [clear: 0 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> css selector: input[name="username"]]])
11:44:27.912 INFO - Done: [clear: 0 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> css selector: input[name="username"]]]
11:44:27.917 INFO - Executing: [send keys: 0 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> css selector: input[name="username"]], [k, e, y, s, t, r, o, k, e, s]])
11:44:28.027 INFO - Done: [send keys: 0 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> css selector: input[name="username"]], [k, e, y, s, t, r, o, k, e, s]]
11:44:28.033 INFO - Executing: [find elements: By.cssSelector: input[name="password"]])
11:44:28.102 INFO - Done: [find elements: By.cssSelector: input[name="password"]]
11:44:28.107 INFO - Executing: [clear: 1 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> css selector: input[name="password"]]])
11:44:28.188 INFO - Done: [clear: 1 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> css selector: input[name="password"]]]
11:44:28.193 INFO - Executing: [send keys: 1 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> css selector: input[name="password"]], [p, a, s, s, w, o, r, d]])
11:44:28.274 INFO - Done: [send keys: 1 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> css selector: input[name="password"]], [p, a, s, s, w, o, r, d]]
11:44:28.283 INFO - Executing: [find element: By.xpath: //button[text()="Log In"]])
11:44:28.342 INFO - Done: [find element: By.xpath: //button[text()="Log In"]]
11:44:28.347 INFO - Executing: [click: 2 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> xpath: //button[text()="Log In"]]])
11:44:28.486 INFO - Done: [click: 2 [[FirefoxDriver: firefox on LINUX (ff2bbf8c-8bbe-47ff-8b20-277b3c0572c9)] -> xpath: //button[text()="Log In"]]]
11:44:28.744 INFO - Executing: [find elements: By.cssSelector: .page-nav])
11:44:31.104 INFO - Done: [find elements: By.cssSelector: .page-nav]
11:44:31.359 INFO - Executing: [find elements: By.cssSelector: .page-nav])
11:44:32.829 INFO - Done: [find elements: By.cssSelector: .page-nav]
11:44:33.087 INFO - Executing: [find elements: By.cssSelector: .page-nav])
11:44:33.098 INFO - Done: [find elements: By.cssSelector: .page-nav]
11:44:33.105 INFO - Executing: [find elements: By.cssSelector: span[title="User Agreement"]])
11:44:33.372 INFO - Done: [find elements: By.cssSelector: span[title="User Agreement"]]
11:44:33.385 INFO - Executing: [delete session: 09cb4176-4511-4c59-bf4b-8b79a3239dd0])
11:44:33.453 INFO - Done: [delete session: 09cb4176-4511-4c59-bf4b-8b79a3239dd0]
11:44:33.474 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
11:44:33.474 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
11:44:33.487 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
11:44:33.492 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
11:44:35.376 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]]
11:44:35.380 INFO - Executing: [maximise window])
11:44:35.532 INFO - Done: [maximise window]
11:44:35.537 INFO - Executing: [get: https://localhost:5143/])
11:44:37.709 INFO - Done: [get: https://localhost:5143/]
11:44:37.715 INFO - Executing: [find elements: By.cssSelector: input[name="username"]])
11:44:37.908 INFO - Done: [find elements: By.cssSelector: input[name="username"]]
11:44:37.913 INFO - Executing: [clear: 0 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> css selector: input[name="username"]]])
11:44:38.092 INFO - Done: [clear: 0 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> css selector: input[name="username"]]]
11:44:38.098 INFO - Executing: [send keys: 0 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> css selector: input[name="username"]], [k, e, y, s, t, r, o, k, e, s]])
11:44:38.566 INFO - Done: [send keys: 0 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> css selector: input[name="username"]], [k, e, y, s, t, r, o, k, e, s]]
11:44:38.572 INFO - Executing: [find elements: By.cssSelector: input[name="password"]])
11:44:38.683 INFO - Done: [find elements: By.cssSelector: input[name="password"]]
11:44:38.689 INFO - Executing: [clear: 1 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> css selector: input[name="password"]]])
11:44:38.821 INFO - Done: [clear: 1 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> css selector: input[name="password"]]]
11:44:38.827 INFO - Executing: [send keys: 1 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> css selector: input[name="password"]], [p, a, s, s, w, o, r, d]])
11:44:38.998 INFO - Done: [send keys: 1 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> css selector: input[name="password"]], [p, a, s, s, w, o, r, d]]
11:44:39.003 INFO - Executing: [find element: By.xpath: //button[text()="Log In"]])
11:44:39.159 INFO - Done: [find element: By.xpath: //button[text()="Log In"]]
11:44:39.165 INFO - Executing: [click: 2 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> xpath: //button[text()="Log In"]]])
11:44:39.473 INFO - Done: [click: 2 [[FirefoxDriver: firefox on LINUX (fdaea51d-3a10-4aba-b9b7-709f7e0b37a5)] -> xpath: //button[text()="Log In"]]]
11:44:39.729 INFO - Executing: [find elements: By.cssSelector: .page-nav])
11:44:40.118 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]]
11:44:40.123 INFO - Executing: [maximise window])
11:44:40.187 INFO - Done: [maximise window]
11:44:40.194 INFO - Executing: [get: https://localhost:5143/])
11:44:43.375 INFO - Done: [find elements: By.cssSelector: .page-nav]
11:44:43.565 INFO - Done: [get: https://localhost:5143/]
11:44:43.572 INFO - Executing: [find elements: By.cssSelector: input[name="username"]])
11:44:45.146 INFO - Done: [find elements: By.cssSelector: input[name="username"]]
11:44:45.162 INFO - Executing: [delete session: c02a8008-1364-462e-90af-83d254c8ff83])
11:44:45.422 INFO - Done: [delete session: c02a8008-1364-462e-90af-83d254c8ff83]
```
Notice the dual execution of creating session at 11:44:33.474...

Anyone have an idea how to solve this?

Expected Result: First test case fails, then each test case runs one after the other.

**Comment by charlierudolph** [comment] 2015-07-21 06:50
I believe this type of thing is caused by the step thinking its finished twice. This could be caused by executing the callback twice or by executing the callback while the step also returns a promise (only in 0.5.2 and later, see #367)

**Comment by cades** [comment] 2015-07-28 11:06
+1
0.5.2 only, 0.5.0 & 0.5.1 is fine

**Comment by jbpros** [comment] 2015-07-29 07:36
@064678147 are you writing your stepdefs in coffeescript there?

Because, yes, it looks like #359 wasn't such a good idea, after all.

I think this is a dup of #367.

**Comment by 064678147** [comment] 2015-07-29 15:37
@jbpros I'm writing my step defs in javascript

**Comment by 064678147** [comment] 2015-08-20 19:09
for me it looks like none of [0.5.0, 0.5.1, 0.5.2] work...

**Comment by 064678147** [comment] 2015-08-20 19:15
Looks like a webdriverio update made it fail gracefully again.

**Comment by charlierudolph** [comment] 2015-09-29 01:22
@richardmcsong closing as it appears solved. I assume this was caused by the callback getting executed twice as thats what can cause multiple executions. #105 captures the problem

**Closed by charlierudolph** 2015-09-29 01:22 UTC
