### ISSUE TITLE
Step definition strings with forward slashes do not work

### ISSUE THREAD

**Issue by gregoryfabry** [cucumber/cucumber-js#842] opened 2017-05-31 19:31 UTC
Given the following file snippet:
    
    Scenario: step with a slash
      When I have a step with a / forward slash in it

    Scenario: step with no slash
      When I have a step with no forward slash in it

When I run Cucumber.js without implementing the step definitions
And copy the outputted snippets into my step definition file
Then the snippet with no forward slash in it will match
And the snippet with a forward slash in it will not match

Notes: This is version 2.2.0. The output snippets use strings; turning it into a RegEx (and escaping the forward slash) is one way to solve this issue.

**Comment by charlierudolph** [comment] 2017-06-01 05:10
I am unable to reproduce. The snippet it suggests to me is:
```js
Given('I have a step with a / forward slash in it', function (callback) {
  // Write code here that turns the phrase above into concrete actions
  callback(null, 'pending');
});
```
Adding that to my step definition file, it matches.

**Comment by gregoryfabry** [comment] 2017-06-01 16:51
I realized that this behavior only occurs when there is a forward slash with no spaces surrounding it. I created a repository that replicates this behavior on my machine. This is Windows 10, by the way.

git clone, npm install, npm test: https://github.com/gregoryfabry/cucumberjs-842-example

**Comment by gregoryfabry** [comment] 2017-06-01 16:51
@charlierudolph not sure how to reopen the issue.

**Comment by charlierudolph** [comment] 2017-06-01 16:53
The forward slash has special meaning when not surrounded by spaces: https://docs.cucumber.io/cucumber-expressions/#alternative-text

**Comment by gregoryfabry** [comment] 2017-06-01 16:57
Are forward slashes valid in the Gherkin language? In that case, I would imagine that the generated snippets for a line with a forward slash should be a regex instead of a string because otherwise the snippet doesn't match the line it was generated from.

**Comment by charlierudolph** [comment] 2017-06-02 02:16
@aslakhellesoy want to bring you into the loop. Say a step text is `Given a/b`. Then the generated cucumber snippet should be `a\/b` in order to avoid the cucumber-expressions from treating it as alternative text.

**Comment by gregoryfabryhs** [comment] 2017-06-02 13:36
If the Cucumber snippet isn't a RegEx I don't believe that escaping the forward slash will work:

        When I have a step with a forward/slash in it

Isn't matched by
    When('I have a step with a forward\/slash in it', function (callback) {
      // Write code here that turns the phrase above into concrete actions
      callback(null, 'pending');
    });

or

  When('I have a step with a forward\\/slash in it', function (callback) {
      // Write code here that turns the phrase above into concrete actions
      callback(null, 'pending');
    });

**Comment by gregoryfabry** [comment] 2017-06-02 13:38
If the Cucumber snippet isn't a RegEx I don't believe that escaping the forward slash will work:

        When I have a step with a forward/slash in it

Isn't matched by

    When('I have a step with a forward\/slash in it', function (callback) {
      // Write code here that turns the phrase above into concrete actions
      callback(null, 'pending');
    });

or

    When('I have a step with a forward\\/slash in it', function (callback) {
      // Write code here that turns the phrase above into concrete actions
      callback(null, 'pending');
    });

**Comment by aslakhellesoy** [comment] 2017-06-02 14:54
If you need to use a `/` for other things than alternation I suggest you use a `RegExp` instead of a cucumber expression. 

Cucumber expressions don't support escaping of special characters, and I'm not sure I want to build it in either.

**Comment by aslakhellesoy** [comment] 2017-06-02 14:58
So instead of this:

```javascript
// Strings are interpreted as cucumber expressions. No escaping supported
When('I have a step with a forward/slash in it', ...)
```

Do this:

```javascript
// Regular Expressions support escaping
When(/I have a step with a forward\/slash in it/, ...)
```

**Comment by aslakhellesoy** [comment] 2017-06-02 15:01
I do see the problem of generating snippets that don't match though, so we should either:

* Add support for escaping in cucumber expressions
* Generate regexp snippets when there are special characters

I need to mull this over. If it's easy to implement escaping we can probably do that.

**Comment by aslakhellesoy** [comment] 2017-06-08 08:36
I'm closing this issue since it's duplicated by cucumber/cucumber#107

**Closed by aslakhellesoy** 2017-06-08 08:36 UTC
Labels: bug in dependency
