### ISSUE TITLE
Support glob pattern in --require

### ISSUE THREAD

**Issue by csi-lk** [cucumber/cucumber-js#895] opened 2017-08-11 01:03 UTC
Related: https://github.com/cucumber/cucumber-js/issues/645

In previous ticket @charlierudolph asked for a use case, for our codebase I am looking to have our structure set up as:

```
/src
| +--views
|   +--login
|        login.js        # the code
|        login.scss      # styling
|        login.spec.js   # unit test
|        login.feature   # cucumber feature file
|        login.steps.js  # cucumber step definition
| +--functional-tests
|    routes.js           # global step definition
```

To keep everything scoped

In the CLI I am trying to to run the command as:

```
./node_modules/cucumber/bin/cucumber.js ./src/ --require ./functional-tests/*.js ./src/views/**/*.steps.js --compiler support.js:babel-register
```

Which doesn't work as it can't do glob matching (no such file or directory)

If anyone has a workaround for this i'd appreciate it

Cheers

**Comment by Si1kIfY** [comment] 2017-08-11 01:37
Figured out a workaround with unix, is a bit messy but works for the moment

```
find . -name *.steps.js | awk '{print " --require " $0}' ORS=' ' | xargs ./node_modules/cucumber/bin/cucumber.js ./src/ --compiler support.js:babel-register
```

**Comment by charlierudolph** [comment] 2017-08-29 05:08
I've never seen a setup like that where features and step definitions are inline with source. How has that worked for you? I don't see why features would be inline as they have always been a higher level test for me and thus are testing more than a single component.

**Comment by Si1kIfY** [comment] 2017-08-29 05:35
> features and step definitions are inline with source 

When I plan a new project with > 10 devs assigned I try to atomise the development process as much as possible (ala [Atomic Design principles](http://bradfrost.com/wp-content/uploads/2013/06/atomic-design.png)), elements / components etc. are created as seperate folders with seperate visual regression tests and unit tests. Because the functional tests are run against the views I try to keep the same pattern and split them.

> How has that worked for you?

Comparing a few project iterations I've found more scenarios get covered and less gets lost doing it this way rather than keeping them higher up, YMMV 😇

**Comment by charlierudolph** [comment] 2018-01-04 01:56
Closing as this will be required as part of #985

**Closed by charlierudolph** 2018-01-04 01:56 UTC
