### ISSUE TITLE
Any way to end a feature test successfully when nodejs hangs?

### ISSUE THREAD

**Issue by totty90** [cucumber/cucumber-js#296] opened 2015-01-20 00:35 UTC
I have a quite big app that hangs because of sockets. It doesn't end the feature and cucumber hangs. Is possible to force end the feature but with success?

**Comment by jbpros** [comment] 2015-02-07 13:29
I can't think of any straightforward way to do that reliably without losing some part of the output from Cucumber. Isn't it possible to close the sockets properly (which would be the right way of doing things anyway)?

**Comment by kAworu** [comment] 2015-02-13 11:53
see also #262

**Comment by kAworu** [comment] 2015-02-13 13:38
I have the same issue as you do. In my case, the problem is that another npm module (connection-mongostore) keep an open connection. The module does not offer any way to close it. While Cucumber hanging is fine when tests are run from the cli it's a real issue with CI (like Jenkins).

Leaving aside the Right Way™ debate, I am not sure that it is reasonable to think that all third parties module will cleanup or offer a way to do it. When one of them does not it's a world of pain to figure out which and why.

@totty90 as a workaround I am stuck using cucumber =0.4.0, which was the latest version that did not hang.

**Comment by totty90** [comment] 2015-02-13 14:07
@kAworu why the newer version hangs?

**Comment by kAworu** [comment] 2015-02-13 15:07
@totty90 as I've written in #262 the fix is 1da47fb1b2dba20c4bc195f46aeda4df9d408fe1 which reference #120.

**Comment by jbpros** [comment] 2015-07-03 21:54
Should be fixed by 23ff8608417b542c8c775c2ac5914e232b8c5dfa. Please reopen is necessary.

**Closed by jbpros** 2015-07-03 21:54 UTC
