### ISSUE TITLE
setDefinitionFunctionWrapper used for overall Scenario timeout

### ISSUE THREAD

**Issue by dambler** [cucumber/cucumber-js#1741] opened 2021-07-29 15:02 UTC
After upgrading to 7.3.1, I can see the deprecation notice for the `setDefinitionFunctionWrapper` method, suggesting to use the new `BeforeStep` and `AfterStep` methods instead.

I use `setDefinitionFunctionWrapper` in a project to control Scenario timeouts and I am at a loss with working out how I can achieve similar behaviour using these new step hooks.

The general gist of the code I am currently using is:

```
const MAX_DURATION_IN_MS = 90_000;
let timeout: NodeJS.Timeout | undefined;
let maxEndtime = Date.now() + MAX_DURATION_IN_MS;

const clearExecutionTimeout = () => {
  if (!timeout) return;

  clearTimeout(timeoutId);
  timeout = undefined;
};

setDefinitionFunctionWrapper(
  (fn: Function) =>
    async function (this: any, ...args: any[]) {
      // Only actual test steps should use this timeout value.
      const shouldUseTimeOut =
        args[0]?.pickle === undefined &&
        args[0]?.result === undefined &&
        maxEndtime !== undefined;

      const promises: Promise<void | string>[] = [fn.apply(this, args)];

      if (shouldUseTimeOut) {
        promises.push(
          new Promise((resolve) => {
            timeout = global.setTimeout(
              () => resolve('skipped'),
              Math.max(maxEndtime! - Date.now(), 0),
            );

            return timeoutId;
          }),
        );
      }

      const result = await Promise.race(promises);
      clearExecutionTimeout();

      return result;
    },
);

Before(() => {
  maxEndtime = Date.now() + MAX_DURATION_IN_MS;
});
```

I am doing this as I am running these Scenarios inside an AWS lambda and I need to control their execution timeouts to ensure that we get feature JSON output before the handler exits completely.

I have tried setting a timeout in a `BeforeStep` hook, but retuning 'skipped' there is ignored. I have tried throwing inside a timeout also, but that causes the process to exit non-cleanly (i.e. the json report is not generated).

Any ideas if what I am trying to do is actually possible anymore without `setDefinitionFunctionWrapper`?

**Comment by aurelien-reeves** [comment] 2021-07-30 07:30
The built-in timeout feature of `cucumber-js` do not work with your case?

https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/timeouts.md

**Comment by dambler** [comment] 2021-07-30 11:09
From what I understand, built in timeouts cannot be applied to scenarios as a whole. I need an individual scenario not to take over X seconds.

**Comment by aurelien-reeves** [comment] 2021-07-30 11:36
You should give it a try
I am pretty sure you can use it at the scenario level

**Comment by dambler** [comment] 2021-07-30 11:53
Where exactly would you place it to make it affect the entire scenario? Just to clarify, I want the scenario to take no more than, for example 90 seconds, but the steps within the scenario can take as long as they want (within that time frame).

**Comment by aurelien-reeves** [comment] 2021-07-30 12:06
In the Before hook as explained in the documentation

**Comment by aurelien-reeves** [comment] 2021-07-30 12:25
As the doc says, we can set that `timeout` option in a `Before` hook, or in a step.

The `Before` hook apply to the whole scenario, not just for a step, so set your timeout in the `Before` hook, that should fit your needs.

**Comment by dambler** [comment] 2021-07-30 12:49
Using the [nodejs example](https://github.com/cucumber/cucumber-js/blob/main/docs/nodejs_example.md), I added a delay method:

```
const delay = (ms) => new Promise((res) => setTimeout(res, ms));
```

A set a timeout in a Before hook like so:

```
Before({ timeout: 100 }, function () {
  console.log("Hook");
});
```

I alter a step definition like so:

```
Given("a variable set to {int}", async function (number) {
  await delay(5000);
  this.setTo(number);
});
```

When I execute the test, the test does _not_ timeout after 100ms. It's quite possible I am missing something or doing something incorrectly, but I am just not seeing the behaviour you are saying should work!

**Comment by aurelien-reeves** [comment] 2021-07-30 21:38
Could you share the whole code of your test please?

**Comment by dambler** [comment] 2021-07-31 07:54
Sure - here is the code. Its basically just a very minor modification to the NodeJS example in the repo.

```
#features/support/world.js
const { setWorldConstructor } = require("@cucumber/cucumber");

class CustomWorld {
  constructor() {
    this.variable = 0;
  }

  setTo(number) {
    this.variable = number;
  }

  incrementBy(number) {
    this.variable += number;
  }
}

setWorldConstructor(CustomWorld);
```

```
#features/support/steps.js
const { Given, When, Then } = require("@cucumber/cucumber");
const assert = require("assert").strict;

const delay = (ms) => new Promise((res) => setTimeout(res, ms));

Given("a variable set to {int}", async function (number) {
  await delay(5000);
  this.setTo(number);
});

When("I increment the variable by {int}", function (number) {
  this.incrementBy(number);
});

Then("the variable should contain {int}", function (number) {
  assert.equal(this.variable, number);
});
```

```
#features/support/hooks.js
const { Before } = require("@cucumber/cucumber");

Before({ timeout: 100 }, function () {
  console.log("Hook");
});
```

```
#features/simple_math.feature
Feature: Simple maths
  In order to do maths
  As a developer
  I want to increment variables

  Scenario: easy maths
    Given a variable set to 1
    When I increment the variable by 1
    Then the variable should contain 2

  Scenario Outline: much more complex stuff
    Given a variable set to <var>
    When I increment the variable by <increment>
    Then the variable should contain <result>

    Examples:
      | var | increment | result |
      | 100 |         5 |    105 |
      |  99 |      1234 |   1333 |
      |  12 |         5 |     17 |
```

**Comment by aurelien-reeves** [comment] 2021-08-02 07:42
Thanks.

So, indded, I was totally wrong 😰
The timeout is for the hook itself, not for the whole scenario

I continue looking into your issue...

**Comment by aurelien-reeves** [comment] 2021-08-02 10:18
I've been able to have something that looks a little bit like your original code:

```javascript

const MAX_DURATION_IN_MS = 500;
let timeout = undefined;
let maxEndtime = Date.now() + MAX_DURATION_IN_MS;

const clearExecutionTimeout = () => {
  if (!timeout) return;

  clearTimeout(timeout);
  timeout = undefined;
};

Before(function (testStep) {
  maxEndtime = Date.now() + MAX_DURATION_IN_MS;
});

BeforeStep(async function (test) {
  timeout = global.setTimeout(() => {
      throw 'timedout'
    },
    Math.max(maxEndtime - Date.now(), 0)
  )

  return Promise.resolve()
})

AfterStep(function ({result}) {
  clearExecutionTimeout()
})
```

However I've not been able to set the step has being `skipped`. I've only succeeded into rejecting the Promise so it result into an error, thus a failed step. I hope that would still help?

**Comment by dambler** [comment] 2021-08-02 10:42
Thanks for taking the time to look into this - I tried something similar and the issue with this approach is the exit isn't clean, i.e. my formatters are not run, and I need the JSON output for my reporting stack.

Unfortunately the deprectation of this method (without a viable workaround) may require me to not upgrade to future versions of Cucumber, which sucks!

**Comment by aurelien-reeves** [comment] 2021-08-02 12:00
> Thanks for taking the time to look into this - I tried something similar and the issue with this approach is the exit isn't clean, i.e. my formatters are not run, and I need the JSON output for my reporting stack.
> 

That's an issue on your side. I've just tested with the code I've posted earlier, and the exit is clean and the formatters are properly executed.

```shell
$ npm test

> test
> cucumber-js --publish-quiet --format=json

[
  {
    "description": "",
    "elements": [
      {
        "description": "",
        "id": ";sample-test-case",
        "keyword": "Scenario Outline",
        "line": 4,
        "name": "Sample test case",
        "steps": [
          {
            "keyword": "Before",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 0
            }
          },
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 5,
            "name": "this is a test case",
            "match": {
              "location": "features/step_definitions/steps.js:3"
            },
            "result": {
              "status": "passed",
              "duration": 0
            }
          },
          {
            "arguments": [
              {
                "rows": [
                  {
                    "cells": [
                      "Test Child Tag 1"
                    ]
                  }
                ]
              }
            ],
            "keyword": "When ",
            "line": 6,
            "name": "I have the following data table",
            "match": {
              "location": "features/step_definitions/steps-2.js:34"
            },
            "result": {
              "status": "failed",
              "duration": 499000000,
              "error_message": "timedout"
            }
          },
          {
            "arguments": [],
            "keyword": "Then ",
            "line": 8,
            "name": "a JSON report will be generated",
            "match": {
              "location": "features/step_definitions/steps-2.js:40"
            },
            "result": {
              "status": "skipped",
              "duration": 0
            }
          }
        ],
        "tags": [
          {
            "name": "@parent_tag",
            "line": 3
          },
          {
            "name": "@*test",
            "line": 3
          },
          {
            "name": "@child_tag_1",
            "line": 10
          }
        ],
        "type": "scenario"
      }
    ],
    "id": "",
    "line": 1,
    "keyword": "Feature",
    "name": "",
    "tags": [],
    "uri": "features/test.feature"
  }
]%      
```

**Comment by dambler** [comment] 2021-08-03 06:22
Thanks @aurelien-reeves, I'll try and debug my project a bit to see if I can see why I am not exiting cleanly.

Regarding why I need timeout per scenario - these tests are executed inside an AWS lambda with strict timeouts set. For example, an invocation will timeout after 2 minutes, so I set my Scenario to be maximum 1 minute 30 seconds to ensure that I get all my reporting data.

**Comment by aurelien-reeves** [comment] 2021-08-03 07:01
> Regarding why I need timeout per scenario - these tests are executed inside an AWS lambda with strict timeouts set. For example, an invocation will timeout after 2 minutes, so I set my Scenario to be maximum 1 minute 30 seconds to ensure that I get all my reporting data.
>

Ok, got it, thanks

@davidjgoss @charlierudolph is there a way to dynamically set the hooks and steps timeouts rather than with a static value in the options?

**Comment by davidjgoss** [comment] 2021-08-09 22:48
> is there a way to dynamically set the hooks and steps timeouts rather than with a static value in the options?

I don't think so, because the support code library is finalised before execution.

I'd probably suggest setting a timer on the `World` (since that is unique per scenario) in the constructor, then checking in on that in a `BeforeStep` and throwing/skipping if too much time has passed. I guess the original solution using the function wrapper is more precise because it will race the step code and bail as soon as the time limit is reached. Do you have particularly long-running steps @dambler?

**Comment by dambler** [comment] 2021-08-11 07:56
I don't especially have long running steps, the problem is the environment that these tests are executed in (AWS lambdas). I'll experiment with using `World` to see if I can get anything suitable.

**Comment by aurelien-reeves** [comment] 2021-09-08 06:39
@dambler have you been able to use the BeforeStep/AfterStep to manage your timeout?

**Comment by davidjgoss** [comment] 2021-09-20 23:54
Going to close this as a duplicate of #1772 - we have a couple of similar requests re unusual use cases for the step wrapper.

We discussed recently in the core team and the decision was to keep `setDefinitionFunctionWrapper` for 8.0.0, but keep it deprecated and also remove the support for generator step definitions to simplify things. We hope to address the use cases in a cleaner way and then remove in a future major release.

**Closed by davidjgoss** 2021-09-20 23:54 UTC
Labels: :question: question
