### ISSUE TITLE
Build issues for typescript

### ISSUE THREAD

**Issue by automatekitbox** [cucumber/cucumber-js#1491] opened 2020-12-04 20:41 UTC
node_modules/@cucumber/messages/dist/src/index.d.ts:9:25 - error TS2732: Cannot find module '../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension

9 import { version } from '../package.json';
                          ~~~~~~~~~~~~~~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:642:35 - error TS2304: Cannot find name 'Long'.

642                 seconds?: (number|Long|null);
                                      ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:658:41 - error TS2304: Cannot find name 'Long'.

658                 public seconds: (number|Long);
                                            ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:738:35 - error TS2304: Cannot find name 'Long'.

738                 seconds?: (number|Long|null);
                                      ~~~~

node_modules/@cucumber/messages/dist/src/messages.d.ts:754:41 - error TS2304: Cannot find name 'Long'.

754                 public seconds: (number|Long);
                                            ~~~~

**Comment by automatekitbox** [comment] 2020-12-05 04:00
Seeing above issues while building. Please suggest

**Comment by davidjgoss** [comment] 2020-12-06 13:16
Hey @automatekitbox, can you clarify if this is when building cucumber itself, or consuming it in a TypeScript project? If the latter would you be able to put a minimal repro up?

**Comment by christian-bromann** [comment] 2021-01-14 18:30
@davidjgoss it's when using Cucumber in a TS project. Running into the same issues but struggle to create a minimal reproducible example. My workaround is to [load the long module](https://github.com/webdriverio/webdriverio/blob/cb-typing-cleanup/packages/wdio-cucumber-framework/src/index.ts#L40-L44) so it is loaded by TS.

**Comment by davidjgoss** [comment] 2021-01-20 01:04
Closing as a duplicate of #1519 - we'll definitely get this addressed there.

**Closed by davidjgoss** 2021-01-20 01:04 UTC
