### ISSUE TITLE
TypeError: e.scrollIntoView is not a function

### ISSUE THREAD

**Issue by nzhenry** [cucumber/cucumber-js#526] opened 2016-03-01 17:09 UTC
I tried running cucumber.js with the sample feature and step definition from your readme file and got this error:

  Scenario: Reading documentation                   # features/my_feature.feature:7
    Given I am on the Cucumber.js GitHub repository # features/step_definitions/my_step_definitions.js:3
      TypeError: e.scrollIntoView is not a function
          at n (https://assets-cdn.github.com/assets/frameworks-96e29b697be2d5e4c062e40ce2dab35f90b4cd378cfbbcd6dd51a3f280e7d426.js:7:11676)
          at Object.r [as scrollToFragmentTarget] (https://assets-cdn.github.com/assets/frameworks-96e29b697be2d5e4c062e40ce2dab35f90b4cd378cfbbcd6dd51a3f280e7d426.js:7:11773)
          at https://assets-cdn.github.com/assets/github-2e7a70c71fffe6d08242c7318652482164ab584a70e982bc124fc25b4408fa20.js:2:7038
          at r (https://assets-cdn.github.com/assets/frameworks-96e29b697be2d5e4c062e40ce2dab35f90b4cd378cfbbcd6dd51a3f280e7d426.js:6:17060)
          at https://assets-cdn.github.com/assets/frameworks-96e29b697be2d5e4c062e40ce2dab35f90b4cd378cfbbcd6dd51a3f280e7d426.js:6:16403
          at s (https://assets-cdn.github.com/assets/frameworks-96e29b697be2d5e4c062e40ce2dab35f90b4cd378cfbbcd6dd51a3f280e7d426.js:6:16060)
          at HTMLDocument.a (https://assets-cdn.github.com/assets/frameworks-96e29b697be2d5e4c062e40ce2dab35f90b4cd378cfbbcd6dd51a3f280e7d426.js:6:16088)
          at callListeners (/Users/a_user/node_project/node_modules/zombie/node_modules/jsdom/lib/jsdom/events/EventTarget.js:176:34)
          at dispatchPhase (/Users/a_user/node_project/node_modules/zombie/node_modules/jsdom/lib/jsdom/events/EventTarget.js:159:7)
          at HTMLDocument.EventTarget.dispatchEvent (/Users/a_user/node_project/node_modules/zombie/node_modules/jsdom/lib/jsdom/events/EventTarget.js:115:3)
          in https://github.com/cucumber/cucumber-js

**Comment by jmauerhan** [comment] 2016-03-02 21:10
Same

**Comment by pmcelhaney** [comment] 2016-03-05 18:25
I'm having the same problem. I created an example repo so you can see all of my code and try it out for yourself.

https://github.com/pmcelhaney/cucumber-test

**Comment by marcincharezinski** [comment] 2016-04-20 09:11
Same here

**Comment by charlierudolph** [comment] 2016-08-29 05:04
Closing as a duplicate of #561 where we will update the documentation to use selenium.

**Closed by charlierudolph** 2016-08-29 05:04 UTC
