### ISSUE TITLE
'skipped' status returned from When is not preventing the execution of Then step

### ISSUE THREAD

**Issue by sfdcale** [cucumber/cucumber-js#1312] opened 2020-04-24 03:30 UTC
I am struggling to skip the execution of `Then` step when status returned from `When` method is `'skipped'`:

**Snippet1**:
This is not working(`Then` step is executed)
```
this.When(/^Status returned is Skipped$/, {retry: 2}, () => {
    let output = resultOfSomeOperation();
    if(output > 0){
        return 'skipped';
    }
});
```

**Snippet2**:
This is working(`Then` step is not executed)
```
this.When(/^Status returned is Skipped$/, {retry: 2}, () => {
    let output = resultOfSomeOperation();
    if(output > 0){
        return 'pending';
    }
});
```

Why snippet1 is not skipping the execution of `Then` step?

My ultimate goal is to skip the execution of `Then` step based on the results of some operation in `When` step.

**Comment by charlierudolph** [comment] 2020-05-02 21:53
Auhh. The original requirements for the "skipped" feature involved being able to skip a scenario from a before hook. This seems like a valid use case and something that needs to be fixed.

**Comment by tibawatanabe** [comment] 2020-05-21 01:21
Hum... so is the example from `skipped_steps.feature` not valid/not something we should use as reference? Considering its content I'd assume that a skipped `Given` would work regardless of a hook.

**Comment by davidjgoss** [comment] 2021-07-14 15:53
This feature describes and tests the current behaviour around "skipped" https://github.com/cucumber/cucumber-js/blob/main/features/skipped_steps.feature - we'd be adding a couple more scenarios there to cover skipping from steps.

The status is being set on the basis of the "skipped" result from the step code here https://github.com/cucumber/cucumber-js/blob/main/src/runtime/step_runner.ts#L66 - so the orchestration a level up in https://github.com/cucumber/cucumber-js/blob/main/src/runtime/test_case_runner.ts is probably where we need to make changes.

**Comment by RukenaG** [comment] 2022-01-19 19:42
@mattwynne and I tried to reproduce the scenario but surprisingly, it doesn't fail. Here's a link: https://github.com/cucumber/cucumber-js/compare/main...RukenaG:fix-%231312?

@sfdcale, do you see anything wrong with our implementation of the scenario?

@davidjgoss is it possible this bug has been fixed accidentally since this bug was reported?

**Comment by davidjgoss** [comment] 2022-02-18 08:14
@RukenaG so sorry for the late reply! The scenario you added looks great. Would you be okay to raise a pull request? We'll probably need to update some docs at the same time.

Yeah looking now, it's very possible this happened by accident, probably as part of the big rework to use the messages protocol.

**Comment by davidjgoss** [comment] 2022-05-30 07:47
Closing this as per discussion the current behaviour includes skipping at the step level.

@gloryCU would still be happy to take a PR for that scenario, as that's valuable coverage and documentation.

**Closed by davidjgoss** 2022-05-30 07:47 UTC
Labels: :thinking: cannot reproduce
